server:
  port: 8080
  host: 127.0.0.1

app:
   debug: true
   datasource:
    url: postgres://postgres:postgres@localhost:5432/postgres
    #  url: postgres://kuroneko:kuroneko@10.10.201.24:7001/rust_demo
    dbPoolLen: 32
    dbPoolTimeout: 60

logging:
  level: debug
  dir: logs/
  rolling: day
  keepType: KeepNum(120)
  packCompress: gzip
  chanLen: 100000

