server:
  port: 8080
  host: 127.0.0.1

app:
   debug: true
   datasource:
#    url: postgres://postgres:postgres@localhost:5432/postgres
    url: postgres://kuroneko:kuroneko@10.10.201.24:7001/rust_demo
    dbPoolLen: 32
    dbPoolTimeout: 60
   security:
     whiteList:
       - /demo
       - /oauth
       - /favicon.ico
       - /ui
     token:
       prefix: Bearer
       expire: 360
       issuer: dingdangmaoup
   redis:
#     url: redis://root:123456@127.0.0.1:6379/0
     url: redis://10.10.201.24:6379/0
logging:
  level: debug
  dir: logs/app.log
  rolling: day
  keepType: KeepNum(120)
  packCompress: gzip
  chanLen: 100000

