### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=RustRover

###

POST localhost:8080/user
Content-Type: application/json

{
  "username": "dingdangmaoup",
  "password": "123456",
  "nickName": "dingdingdangdang",
  "phone": "17676887654",
  "email": "asda@qq.com",
  "sex": 1
}

###
GET localhost:8080/user?pageSize=10&pageNo=2&username=d&orderBy=id&nickName=admin
Authorization: Bearer {{token}}

###
GET localhost:8080/ui
Authorization: Bearer {{token}}

